version:          "0025--17-Aug-2022"
copyright:        "2021-2022"
title:            "Github Page"
author:           "Ruben Tanoey"
address:          "Jakarta."
description:
  OS 2022 Student
disclaimer:
  Trying my best.
keywords:         "jekyll, testing"
navbarlinks:
- navbar:         "Home"
  link:           "/"
- navbar:         "GitHub"
  link:           "https://github.com/rubentanoey/os222"
- navbar:         "mylog.txt"
  link:           "https://github.com/rubentanoey/os222/blob/main/TXT/mylog.txt"
- navbar:         "TarBall"
  link:           "https://os.vlsm.org/Log/rubentanoey.tar.bz2.txt"
lang:             "en-US"
sitemap:          "true"
markdown:         "kramdown"
urlweb:           "https://rubentanoey.github.io/os222/"
urlcontact:       "TBA"
urlgithub:        "https://github.com/rubentanoey/os222"
google_analytics: "G-KPSLWHN6H7"
plugins:
- jekyll-sitemap
- jekyll-seo-tag
- jekyll-paginate
defaults:
- scope:
    path:    ""
  values:
    layout:  "default"
github:
- metadata

